trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    python -m unittest discover
  displayName: 'Run tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<your-azure-subscription>'
    appName: '<your-app-name>'
    package: .
